PersonSearch/urls.py
from django.contrib import admin
from django.urls import path

from searchapp.views import admin, account, meter, detect, identify, about
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [

    # 配置media
    re_path(r'^data/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='data'),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),  # 注销
    path('image/code/', account.image_code),  # 生成图像验证码

    # 用户
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('user/add/', admin.user_add),   # 用户注册
    path('admin/<int:aid>/edit/', admin.admin_edit), # 管理员页面
    path('user/<int:aid>/edit/', admin.user_edit),  # 用户更新
    path('admin/del/', admin.admin_del), # 管理员删除用户
    path('admin/<int:aid>/reset/', admin.admin_reset), # 管理员重置密码
    path('user/<int:aid>/reset/', admin.user_reset),  # 用户更新密码

    # 测试用欢迎界面
    # path('', meter.index),  # 欢迎界面

    # 行人检测
    path('', detect.person_list),  # 行人列表（设置为成为默认的启动地址）
    path('person/add/', detect.person_add),                # 上传包含行人的图像
    path('person/<int:yid>/del/', detect.person_del),      # 删除包含行人的图像
    path('person/<int:yid>/detect/', detect.person_detect),    # 行人检测
    path('person/<int:yid>/display/', detect.person_display),   # 检测后的图像显示

    # 行人搜索
    path('reid/', identify.search_list),   # 重识别结果列表，最多显示5个，后期改为用户自行设定
    path('reid/identify/', identify.identify),   # 上传包含行人的图像
    path('reid/<int:yid>/display/', identify.source_display),   # 识别后的来源图像显示

    # 关于
    path('about/', about.story),

]

searchapp/models.py
from django.db import models
from django.utils.timezone import now
import datetime
import django
from django.db.models import JSONField
import numpy as np
from django.core.files.base import ContentFile
from io import BytesIO


class Admin(models.Model):
    # 用户
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    role_choices = (
        (1, "用户"),
        (2, "管理员")
    )
    role = models.SmallIntegerField(verbose_name="角色", choices=role_choices, default=1)

    name = models.CharField(verbose_name="姓名", max_length=16)
    age = models.IntegerField(verbose_name="年龄")
    # 在django中做的约束
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    mobile = models.CharField(verbose_name="手机号", max_length=32)
    create_time = models.DateField(verbose_name="创建时间", default=now)

    def __str__(self):  # 输出对象时显示username
        return self.username


def default_img_result():
    return [[]]


class PersonSet(models.Model):
    # 行人信息表
    # 本质上数据库也是CharField，会自动保存数据。  upload_to='original_imgs/' 表示文件会自动保存在data目录下的original_imgs目录中
    img = models.FileField(verbose_name="行人图片", max_length=128, upload_to='original_imgs/')

    # img_result decimal(10,2) 小数
    img_result = JSONField(verbose_name="识别结果", default=default_img_result)

    img_name = models.CharField(verbose_name="图片名称", max_length=128)

    processed_img = models.FileField(verbose_name="检测图片", max_length=128, upload_to='processed_imgs/', null=True)

    # 会在数据库表中自动创建admin_id字段
    admin = models.ForeignKey(verbose_name="用户", to="Admin", to_field="id", on_delete=models.CASCADE)


class BoxSet(models.Model):
    # 行人信息表
    # 本质上数据库也是CharField，会自动保存数据。  upload_to='boxes_imgs/' 表示文件会自动保存在data目录下的boxes_imgs目录中
    img = models.FileField(verbose_name="检测框", max_length=128, upload_to='boxes_imgs/')  # 路径

    img_info = models.CharField(verbose_name="图片信息", max_length=128, default='')

    # 来源图片id
    source_id = models.ForeignKey(verbose_name="用户", to="PersonSet", to_field="id", on_delete=models.CASCADE,
                                  related_name="boxes", null=True)

    # 特征向量文件
    feature = models.FileField(verbose_name="特征向量", upload_to='npy_files/', null=True)

    # 会在数据库表中自动创建admin_id字段
    admin = models.ForeignKey(verbose_name="用户", to="Admin", to_field="id", on_delete=models.CASCADE)

searchapp/views/about.py
from django.shortcuts import render, HttpResponse, redirect
from searchapp.utils.pagination import Pagination
from searchapp.utils.drawio import drawbox
from searchapp import models
from searchapp.utils.bootstrap import BootStrapModelForm
from django import forms
from django.http import JsonResponse

import os
import glob
from django.conf import settings
import json


def story(request):
    return render(request, "introduction.html")

searchapp/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from searchapp import models
from searchapp.utils.pagination import Pagination
from django import forms
from searchapp.utils.bootstrap import BootStrapForm
from searchapp.utils.encrypt import md5
from searchapp.utils.img_code import check_code
# 生成验证码时用
from io import BytesIO
import os
from django.conf import settings


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True    # 必填
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),   # render_value=True表示密码输入后不会置空
        required=True    # 必填
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True  # 必填
    )

    def clean_password(self):
        pwd_md5 = md5(self.cleaned_data.get("password"))
        return pwd_md5


# class LoginModelForm(forms.ModelForm):
#     class Meta:
#         model = models.Admin
#         labels = ["username","password"]

def login(request):
    req_method = request.method
    if req_method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码
        # print(form.cleaned_data)   # {'username': 'root', 'password': '4876931d2563f86d7abfa501e3a51554','code': 'YLCHV'}

        user_input_code = form.cleaned_data.pop('code')
        img_code = request.session.get('image_code', "")

        if user_input_code.upper() != img_code.upper():
            form.add_error("code", "验证码错误")  # form.add_error主动添加一个错误
            return render(request, 'login.html', {"form": form})

        # 去数据库校验用户名和密码是否正确，获取用户对象、没有数据为None
        # admin = models.Admin.objects.filter(username="xxx",password="xxx").first()
        admin = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin:  # 说明用户名和密码不存在
            # form.add_error("username", "用户名或密码错误")
            form.add_error("password", "用户名或密码错误")     # form.add_error主动添加一个错误
            return render(request, 'login.html', {"form": form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；再写入到session中；
        request.session["info"] = {'id': admin.id, 'username': admin.username, "name": admin.name,'role': admin.get_role_display()}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect("/")
    return render(request, 'login.html', {"form": form})


def logout(request):
    '''注销'''
    request.session.clear()
    return redirect("/login/")


def image_code(request):
    '''生成图像验证码'''

    os.chdir(settings.BASE_DIR)  # 改变工作目录

    # 调用pillow函数，生成图片
    img, code_string = check_code()
    # print(code_string)  # YLCHV 每次都会变

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, format='png')
    stream.seek(0)
    return HttpResponse(stream.getvalue(), content_type='image/png')

searchapp/views/admin.py
from django.shortcuts import render, HttpResponse, redirect
# from my_app.models import Department,UserInfo
from searchapp import models
from searchapp.utils.pagination import Pagination
from searchapp.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm, UserModelForm, UserEditModelForm
from django.http import JsonResponse
# 免除post请求的csrf认证
from django.views.decorators.csrf import csrf_exempt


'''管理员接口'''


# 管理员列表
def admin_list(request):

    # admin = request.session.get("info")
    # admin = request.session["info"]
    # print(admin["id"])   # 8
    # print(admin["name"]) # root

    # 搜索
    data_dict = {}
    # 第二个值为默认值
    # search_data对用户名进行模糊查询
    search_data = request.GET.get("q", "")  # search_data在没传入q值的时候为空
    if search_data: # search_data值不为空时
        data_dict['username__contains'] = search_data

    admin_list = models.Admin.objects.filter(**data_dict)
    print(admin_list)

    # 页码组件类
    page_object = Pagination(request, admin_list, page_size=10)  # 每页最多显示2个数据

    render_data ={
        "search_data": search_data,
        "admin_list": page_object.page_queryset,  # 获取起止页所需数据
        "page_string": page_object.html()  # 页码所需要的html代码
    }

    return render(request, 'admin_list.html', render_data)


from django import forms
from django.core.exceptions import ValidationError
from searchapp.utils.bootstrap import BootStrapModelForm


# 添加管理员
def admin_add(request):
    title = "新建管理员"
    req_method = request.method
    if req_method == 'GET':
        form = AdminModelForm()
        return render(request, 'public_xxx_add.html', {"title": title, "form": form})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():  # 数据验证成功
        # print(form.cleaned_data)  # {'username': 'ttt', 'password': '122', 'confirm_password': '123'}
        form.save()
        return redirect("/admin/list/")
    return render(request, 'public_xxx_add.html', {"title": title, "form": form})


# 更新管理员
def admin_edit(request, aid):
    title = "更新管理员"
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request,'error.html',{"msg": "数据不存在"})
        return redirect("/admin/list/")
    req_method = request.method
    if req_method == 'GET':
        form = AdminEditModelForm(instance=admin)
        return render(request, 'public_xxx_add.html', {"title": title,"form": form})
    form = AdminEditModelForm(data=request.POST,instance=admin)
    if form.is_valid():
        # 因为AdminEditModelForm中只定义了username这一个字段，所以更新时只会更新这一个值
        form.save()
        return redirect("/admin/list/")
    return render(request, 'public_xxx_add.html', {"title": title,"form": form})


# 删除管理员
def admin_del(request):
    aid = request.GET.get("id")
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        return render(request, 'error.html', {"msg": "数据不存在"})
        # return redirect("/admin/list/")
    models.Admin.objects.filter(id=aid).delete()
    return redirect("/admin/list/")


# 重置密码
def admin_reset(request, aid):
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request, 'error.html', {"msg": "数据不存在"})
        return redirect("/admin/list/")
    title = "重置密码 - {}".format(admin.username)
    req_method = request.method
    if req_method == 'GET':
        # form = AdminResetModelForm(instance=admin)      # 更新密码
        form = AdminResetModelForm()      #重置密码不让她看到原来的密码，让其显示为空
        return render(request, 'public_xxx_add.html', {"title": title, "form": form})
    form = AdminResetModelForm(data=request.POST, instance=admin)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, 'public_xxx_add.html', {"title": title, "form": form})


# 用户注册
@csrf_exempt
def user_add(request):
    title = "用户注册"
    req_method = request.method
    if req_method == 'GET':
        form = UserModelForm()
        return render(request, 'register.html', {"title": title, "form": form})
    form = UserModelForm(data=request.POST)
    print(request.POST)
    if form.is_valid():  # 数据验证成功
        # print(form.cleaned_data)  # {'username': 'ttt', 'password': '122', 'confirm_password': '123'}
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})


# 更新用户
def user_edit(request,aid):
    # print('更新用户: ',request.method)
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request,'error.html',{"msg": "数据不存在"})
        return JsonResponse({"status": False, "msg": "数据不存在，请刷新重试"})
    title = "个人资料 - {}".format(admin.name)
    req_method = request.method
    if req_method == 'GET':
        form = UserEditModelForm(instance=admin)
        return render(request, 'my_message.html', {"title": title,"form": form})
    form = UserEditModelForm(data=request.POST,instance=admin)
    # print('form: ',form)
    if form.is_valid():
        # 因为AdminEditModelForm中只定义了username这一个字段，所以更新时只会更新这一个值
        form.save()
        request.session["info"] = {'id': admin.id, 'username': form.instance.username, "name": form.instance.name,'role': admin.get_role_display()}
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})


# 用户重置密码
def user_reset(request, aid):
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request, 'error.html', {"msg": "数据不存在"})
        # return redirect("/yibiao/list/")
        return redirect("/")
    title = "重置密码 - {}".format(admin.username)
    req_method = request.method
    if req_method == 'GET':
        # form = AdminResetModelForm(instance=admin)      # 更新密码
        form = AdminResetModelForm()      #重置密码不让她看到原来的密码，让其显示为空
        return render(request, 'public_xxx_add.html', {"title": title,"form": form})
    form = AdminResetModelForm(data=request.POST,instance=admin)
    if form.is_valid():
        form.save()
        return redirect("/")
        # return redirect("/yibiao/list/")
    return render(request, 'public_xxx_add.html', {"title": title, "form": form})

searchapp/views/identify.py
from django.shortcuts import render, HttpResponse, redirect
from searchapp.utils.pagination import Pagination
from searchapp.utils.drawio import drawbox
from searchapp import models
from searchapp.utils.bootstrap import BootStrapModelForm
from django import forms
from django.http import JsonResponse
from yolov8 import predict

import os
import glob
from django.conf import settings
import json
from io import BytesIO
from utils.imgprocess import read_image
from reid.extractor import getFeature, rank
import numpy as np


'''重识别结果信息表'''
def search_list(request):
    user_id = request.session["info"]["id"]
    image_list = request.session.pop('image_list', None)
    if image_list is None:
        print('None')
        # 无结果返回
        queryset = models.BoxSet.objects.none()
    else:
        # 返回匹配项
        print(image_list)
        queryset = models.BoxSet.objects.filter(id__in=image_list).order_by("-id")
        print(queryset)
    page_object = Pagination(request, queryset, page_size=5)
    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html()  # 生成页码
    }
    return render(request, 'search_list.html', context)


class BoxModelForm(BootStrapModelForm):

    bootstrap_exclude_fields = ["img"]  # 排除不想添加样式的字段

    class Meta:
        model = models.BoxSet
        exclude = ["img_info", "admin", "source_id", "feature"]  # 排除oid和admin后的所有属性（排除订单号和所属用户）
        widgets = {
            "img": forms.FileInput(attrs={"accept": "image/*"}),
            # 限制input file上传类型只能是图片: <input type="file" accept="image/*">
        }


'''上传行人图片'''
def identify(request):
    title = "上传检测框图像"
    req_method = request.method
    if req_method == 'GET':
        form = BoxModelForm()
        return render(request, 'upload_form.html', {"title": title, "form": form})
    form = BoxModelForm(data=request.POST, files=request.FILES)

    if form.is_valid():
        img_object = form.cleaned_data.get('img') or request.FILES.get('img')
        # 图片保存的临时路径
        img_path = os.path.join(settings.MEDIA_ROOT, 'uploads', img_object.name)
        # 确保保存路径存在
        os.makedirs(os.path.dirname(img_path), exist_ok=True)
        # 将图片保存到磁盘上
        with open(img_path, 'wb+') as destination:
            for chunk in img_object.chunks():
                destination.write(chunk)
        # 使用保存的图片路径调用 read_image 函数
        boximage = read_image(img_path)
        feature = getFeature(boximage)
        boximage.close()
        boxes = models.BoxSet.objects.all()
        os.chdir(settings.BASE_DIR)
        feature_arrays = []
        for box in boxes:
            feature_name = str(box.feature)
            feature_path = os.path.join('data', feature_name)
            id = box.id
            a = np.load(feature_path)
            feature_arrays.append((id, a))
        # 查找相似行人图片
        id_list = rank(feature, feature_arrays)
        # 将显示列表id插入会话
        print(id_list)
        request.session['image_list'] = id_list
        # 返回根目录
        return redirect('/reid/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


def source_display(request, yid):
    box = models.BoxSet.objects.filter(id=yid).first()
    if not box:
        return render(request, 'error.html', {"msg": "数据不存在"})
    if not box.source_id:
        return render(request, 'error.html', {"msg": "数据库出现致命错误"})
    image_url = box.source_id.processed_img.url if box.source_id.processed_img.url else None
    return JsonResponse({'image_url': image_url})

searchapp/views/meter.py
from django.shortcuts import render, HttpResponse, redirect


def index(request):
    return render(request, "hello.html")

searchapp/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h1>hello</h1>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            bindStoryEvent();
        })

        function

{% block js %}

searchapp/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px;" class="clearfix">
            {#            <a class="btn btn-success" href="#" target="_blank">  <!-- 在新的页面打开 -->#}
            <a class="btn btn-success" href="/admin/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>

            <div style="float: right;width: 300px;">
                <form href="/admin/list/" method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="关键字"
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                </form>
            </div>

        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 管理员列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>id</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>性别</th>
                    <th>手机号</th>
                    <th>用户角色</th>
                     <th>创建时间</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>

                {% for admin in admin_list %}
                    <tr>
                        <th scope="row">{{ admin.id }}</th>
                        <td>{{ admin.username }}</td>
{#                        <td>{{ admin.password }}</td>#}
                        <td>{{ admin.username }}</td>
                        <td>{{ admin.name }}</td>
                        <td>{{ admin.age }}</td>
                        <td>{{ admin.get_gender_display }}</td>
                        <td>{{ admin.mobile }}</td>
                        <td>{{ admin.get_role_display }}</td>
                        <td>{{ admin.create_time }}</td>
                        <td>
                            <a href="/admin/{{ admin.id }}/reset/" class="btn btn-primary btn-xs">重置密码</a>
                        </td>
                        <td>
                            <a href="/admin/{{ admin.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                            {#                            <a href="/admin/{{ admin.id }}/up/" class="btn btn-primary btn-xs">编辑</a>#}
                            {#                            <a href="/admin/up/?id={{ user.id }}" class="btn btn-primary btn-xs">编辑</a>#}
                            <a href="/admin/del/?id={{ admin.id }}" class="btn btn-danger btn-xs">删除</a>
                        </td>

                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- 分页 -->

        <div class="clearfix">
            <ul class="pagination" style="float: left;">
                {{ page_string }}
            </ul>
        </div>

    </div>
{% endblock %}

searchapp/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

searchapp/templates/hello.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h1>hello</h1>
    </div>
{% endblock %}

searchapp/templates/introduction.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<!-- 使用内联样式使容器内的所有内容居中，同时设置字体为楷体 -->
    <div class="container" style="text-align: center; font-family: 'KaiTi','楷体', STKaiti, '华文楷体', serif;">
        <h1>此系统为1.0版本，老大哥们觉得进步空间很大</h1>
        <img src="{% static 'img/kalki.png' %}" alt="示例图片" style="display: block; margin: 0 auto; width: 1200px; height: auto; margin-bottom: 30px;"> <!-- 假设每行文本高度为15px，这里设置margin-bottom为30px，即两行的高度 -->
    </div>
{% endblock %}

searchapp/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AEGIS</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
        /* 调整模态对话框的最大宽度 */
        .modal-dialog {
            max-width: 100%; /* 或者你想要的任何宽度 */
        }

        /* 使图片在模态对话框内自适应 */
        #modalImg {
            width: 100%; /* 使图片宽度为100% */
            height: auto; /* 保持图片比例 */
        }
    </style>

    {% block css %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">行人搜寻系统</a>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {#                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>#}
                <li><a href="/">行人检测</a></li>
                <li><a href="/reid/">行人搜索</a></li>
                <li><a href="/about/">关于</a></li>
                {% if request.session.info.role == "管理员" %}
                    <!--<li><a href="/model/list/">模板管理</a></li>-->
                    <li><a href="/admin/list/">用户管理</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"> {{ request.session.info.name }} <span class="caret"></span></a>
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false"> lc <span class="caret"></span></a>#}
                    <ul class="dropdown-menu">
                        <li><a href="/user/{{ request.session.info.id }}/edit/">个人资料</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div>
    {% block content %} {% endblock %}
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>

{% block js %}{% endblock %}

</body>
</html>

searchapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary" style="margin-left: 24%;margin-right: 15%;">
        <a href="/user/add/" class="btn btn-primary">注册</a>
    </form>

</div>

</body>
</html>